### ISSUE TITLE
setup.py not working

### ISSUE THREAD

**Issue by D3f0** [machinalis/telegraphy#1]
On pip install telegraphy console shows:

```
Downloading/unpacking telegraphy
  Downloading telegraphy-0.1.2.tar.gz
  Storing download in cache at /home/defo/.pip_download_cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Ft%2Ftelegraphy%2Ftelegraphy-0.1.2.tar.gz
  Running setup.py egg_info for package telegraphy
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/defo/.virtualenvs/coco/build/telegraphy/setup.py", line 5, in <module>
        with open('requirements.txt', 'rb') as fp:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/defo/.virtualenvs/coco/build/telegraphy/setup.py", line 5, in <module>

    with open('requirements.txt', 'rb') as fp:

FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/defo/.virtualenvs/coco/build/telegraphy
Storing complete log in /home/defo/.pip/pip.log
```

**Comment by D3f0** [comment]
It won't be installable until we merge corssbar branch into master.
